"""Builder: emits one_task_manual.ipynb (single task, manual policies from runs_manual.json, no LLM)."""
import json
from pathlib import Path

cells = []
def md(src): cells.append(("markdown", src))
def code(src): cells.append(("code", src))

md(r'''# One task · manual policies (no LLM) · full trace

Run a **single** dailylife user task under DFC, where the policies are **loaded verbatim from
`runs_manual.json`** instead of being generated by an LLM. We monkeypatch
`DFCBenchmarkContext.prepare_task` so it registers the manual policies for the chosen task/variant and
**no LLM policy generation happens**. Everything else (the Qwen agent, the DFC enforcement, AgentDojo's
utility/security scoring) is the real production path.

- **Pick the task** with `TASK_NUM` (default 3) and which **variants** to run (`none` = clean/utility,
  `injection_task_N` = under attack/security).
- Every tool call, every policy decision (allowed / KILLed + which policy), every SOURCE-REQUIRED SQL
  write, and every tool output is logged to `RUN_LOG` and printed.''')

md("## Setup")
code(r'''import os, sys, json, re, time, datetime, glob, importlib
from pathlib import Path

CWD = Path.cwd()
REPO = next((p for p in [CWD, *CWD.parents] if (p / "runs").is_dir()), None)
assert REPO is not None, f"Could not locate runs/. Tried from {CWD}"
RUNS = REPO / "runs"

# make sure the LOCAL dfc package (the one we edit) is importable even if the kernel isn't the .venv
DFC_SRC = REPO / "dfc_agent_framework_integration" / "src"
if DFC_SRC.exists() and str(DFC_SRC) not in sys.path:
    sys.path.insert(0, str(DFC_SRC))

# Bedrock / agent env (mirror the suite worker). NO DFC model is used here (generation is patched out).
os.environ.setdefault("AWS_REGION", "us-east-1")
os.environ.setdefault("BEDROCK_TIMEOUT", "150")
os.environ.setdefault("BEDROCK_MAX_RETRIES", "10")

import logging
logging.getLogger().setLevel(logging.ERROR)
for _n in ("litellm", "LiteLLM", "httpx", "anthropic", "boto3", "botocore", "urllib3"):
    logging.getLogger(_n).setLevel(logging.ERROR)
import litellm
litellm.suppress_debug_info = True
litellm.num_retries = 10

OUT = REPO / "notebooks" / "one_task" / "out"
OUT.mkdir(parents=True, exist_ok=True)
print("repo:", REPO)
print("dfc src:", DFC_SRC, "(exists:", DFC_SRC.exists(), ")")
print("out:", OUT)''')

md("## Config")
code(r'''MANUAL_JSON = REPO / "notebooks" / "final_runs" / "Qwen_3" / "runs_manual" / "runs_manual.json"
_manual = json.load(open(MANUAL_JSON, encoding="utf-8"))

TASK_NUM = 3                                   # <-- the user task to run (user_task_3)
SUITE    = _manual.get("suite", "dailylife")   # taken from the manual file
VER      = "v1.2"
AGENT    = _manual.get("agent", "qwen3-235b")
ATTACK   = "important_instructions"
USER_TASK_ID = f"user_task_{TASK_NUM}"

# Which variants to run.  "none" = clean (utility);  "injection_task_N" = under that attack (security).
# Set to a list like ["none", "injection_task_5"] to run a subset; None = every variant present for this task.
RUN_VARIANTS = ["none", "injection_task_5"]

# DFC defense wiring requires a dfc_model string, but it is NEVER called (prepare_task is patched). Kept only
# so AgentPipeline.from_config builds the DFC pipeline shape.
DFC_MODEL = "us.anthropic.claude-opus-4-8"

from agentdojo.task_suite.load_suites import get_suite
suite = get_suite(VER, SUITE)
user_task = suite.get_user_task_by_id(USER_TASK_ID)
print("suite:", SUITE, "| agent:", AGENT, "| task:", USER_TASK_ID)
print("PROMPT:", user_task.PROMPT)''')

md("## Load + filter the manual policies for this task")
code(r'''def normalize_pgn(pgn: str) -> str:
    """Manual PGNs in the file may be a single line; split each clause onto its own line so
    Policy.from_pgn parses them. (SOURCE REQUIRED handled before SOURCE.)"""
    s = re.sub(r"\s+", " ", (pgn or "").strip())
    for kw in ["SINK", "SOURCE REQUIRED", "SOURCE", "DIMENSION", "CONSTRAINT", "ON FAIL", "DESCRIPTION"]:
        s = re.sub(rf"\s+{kw}\b", "\n" + kw, s)
    return s.strip()

# MANUAL[variant] = {"facts": {...}, "pgns": [normalized pgn, ...]}
MANUAL = {}
for t in _manual["tasks"]:
    if t["user_task"] != USER_TASK_ID:
        continue
    MANUAL[t["variant"]] = {
        "facts": dict(t.get("extracted_facts") or {}),
        "pgns": [normalize_pgn(p["pgn"]) for p in t.get("policies", [])],
    }
assert MANUAL, f"No entries for {USER_TASK_ID} in {MANUAL_JSON}"

print(f"loaded {len(MANUAL)} variant(s) for {USER_TASK_ID}: {sorted(MANUAL)}\n")
_show = "none" if "none" in MANUAL else sorted(MANUAL)[0]
print(f"--- facts (variant '{_show}') ---")
for k, v in MANUAL[_show]["facts"].items():
    print(f"  {k} = {v!r}")
print(f"\n--- {len(MANUAL[_show]['pgns'])} policies (variant '{_show}') ---")
for i, pgn in enumerate(MANUAL[_show]["pgns"]):
    print(f"[{i}] " + pgn.replace("\n", " | "))''')

md("""## Manual policy injection (monkeypatch — NO LLM)

Replaces `DFCBenchmarkContext.prepare_task` so it materializes the manual facts and registers the manual
PGNs for `CURRENT_VARIANT`, instead of calling an LLM. The built context's decision methods are wrapped so
every call is captured in `RUN_LOG`.""")
code(r'''import duckdb
from data_flow_control import Policy, dfc
from dfc_agent_framework_integration.context import DFCBenchmarkContext
from dfc_agent_framework_integration.events import create_event_tables
from dfc_agent_framework_integration.materialize import materialize_preamble_data
from dfc_agent_framework_integration.runtime import DFCRuntimeValidator
from dfc_agent_framework_integration.repair import validate_policy_catalog
from dfc_agent_framework_integration.source_required import build_source_required_index
from dfc_agent_framework_integration.dfc_event_log import DFCEventLog
from dfc_agent_framework_integration.schema import (
    DFCTaskDiagnostics, GeneratedPolicy, PolicyRegistrationRecord, DeletedPolicyRecord)

CURRENT_VARIANT = "none"   # set before each run
RUN_LOG = []               # decision timeline for the CURRENT run
LAST_CONTEXT = []          # stash the built context(s) so we can read diagnostics afterwards

_SINK_RE = re.compile(r"\bSINK\s+(\w+)", re.IGNORECASE)
def _sink_of(pgn):
    m = _SINK_RE.search(pgn or ""); return m.group(1) if m else ""

def _instrument(ctx):
    """Wrap the context decision methods so every tool call / SR write / output lands in RUN_LOG."""
    _v, _o, _sr = ctx.validate_tool_call, ctx.record_tool_output, ctx.execute_source_required_sql
    def validate_tool_call(name, args):
        viol = _v(name, args)
        RUN_LOG.append({"kind": "tool_call", "tool": name, "args": dict(args) if isinstance(args, dict) else args,
                        "blocked": viol is not None,
                        "policies": list(viol.policy_descriptions) if viol is not None else []})
        return viol
    def record_tool_output(name, result):
        RUN_LOG.append({"kind": "tool_output", "tool": name, "preview": str(result)[:300]})
        return _o(name, result)
    def execute_source_required_sql(sql):
        res = _sr(sql)
        RUN_LOG.append({"kind": "source_required_sql", "sql": str(sql)[:300],
                        "status": res.status, "sink": res.sink_relation, "message": (res.message or "")[:200]})
        return res
    ctx.validate_tool_call = validate_tool_call
    ctx.record_tool_output = record_tool_output
    ctx.execute_source_required_sql = execute_source_required_sql

def manual_prepare_task(cls, *, task_context, runtime_schema, llm, dfc_model,
                        functions, agent_model=None, classifier_model=None, event_log=None):
    """Drop-in for DFCBenchmarkContext.prepare_task that registers MANUAL policies (no LLM is called)."""
    event_log = event_log or DFCEventLog(None)
    spec = MANUAL[CURRENT_VARIANT]
    facts = dict(spec["facts"])
    facts.setdefault("no_authorized_destination", "__DFC_NO_AUTHORIZED_DESTINATION__")

    raw_conn = duckdb.connect()
    create_event_tables(raw_conn, runtime_schema)
    materialize_preamble_data(raw_conn, facts, runtime_schema.preamble_relation)
    conn = dfc(raw_conn)

    generated, registered_ids, records, deleted = [], [], [], []
    for i, pgn in enumerate(spec["pgns"]):
        pid = f"manual_{i}"
        gp = GeneratedPolicy(policy_id=pid, pgn=pgn, description="manual policy",
                             applies_to_relation=_sink_of(pgn), rationale="manual (runs_manual.json)")
        generated.append(gp)
        try:
            parsed = Policy.from_pgn(pgn)
            validate_policy_catalog(parsed, runtime_schema)
            conn.register_policy(parsed)
            registered_ids.append(pid)
            records.append(PolicyRegistrationRecord(policy_id=pid, repair_attempts=0, outcome="registered"))
        except Exception as exc:
            deleted.append(DeletedPolicyRecord(policy_id=pid, rationale="manual policy failed to register",
                                               error=repr(exc)[:200]))
            records.append(PolicyRegistrationRecord(policy_id=pid, repair_attempts=0, outcome="deleted"))
            print(f"  [manual] policy {pid} ({_sink_of(pgn)}) FAILED to register: {repr(exc)[:160]}")
    conn.refresh_catalog()

    sr_sinks = build_source_required_index(generated_policies=generated,
                                           registered_policy_ids=registered_ids, runtime_schema=runtime_schema)
    diagnostics = DFCTaskDiagnostics(extracted_facts=facts, generated_policies=generated,
                                     registered_policy_ids=registered_ids, deleted_policies=deleted,
                                     policy_registration=records)
    validator = DFCRuntimeValidator(raw_conn, conn, runtime_schema, generated, registered_ids, facts,
                                    task_id=task_context.task_id, task_prompt=task_context.preamble,
                                    source_required_sinks=sr_sinks)
    ctx = cls(raw_conn=raw_conn, conn=conn, task_context=task_context, runtime_schema=runtime_schema,
              extracted_facts=facts, generated_policies=generated, registered_policy_ids=registered_ids,
              diagnostics=diagnostics, validator=validator, dfc_model=dfc_model, agent_model=agent_model,
              event_log=event_log, source_required_sinks=sr_sinks)
    _instrument(ctx)
    LAST_CONTEXT.append(ctx)
    return ctx

_ORIG_PREPARE = DFCBenchmarkContext.prepare_task
DFCBenchmarkContext.prepare_task = classmethod(manual_prepare_task)
print("manual_prepare_task INSTALLED — policies come from runs_manual.json, no LLM generation.")''')

md("## Build the pipeline (real Qwen agent + real DFC enforcement)")
code(r'''from agentdojo.agent_pipeline.agent_pipeline import AgentPipeline, PipelineConfig
from agentdojo.attacks.attack_registry import load_attack

def build_pipeline():
    return AgentPipeline.from_config(PipelineConfig(
        llm=AGENT, model_id=None, defense="dfc_agent_framework_integration",
        system_message_name=None, system_message=None, suite_name=SUITE, dfc_model=DFC_MODEL))

pipe = build_pipeline()
attack = load_attack(ATTACK, suite, build_pipeline())
print("pipeline:", pipe.name)''')

md("## Run the task")
code(r'''from agentdojo.benchmark import run_task_with_injection_tasks, run_task_without_injection_tasks
from agentdojo.logging import LOGGER_STACK, OutputLogger

variants = RUN_VARIANTS or sorted(MANUAL, key=lambda v: (v != "none", v))

def run_variant(variant):
    global CURRENT_VARIANT
    CURRENT_VARIANT = variant
    RUN_LOG.clear(); LAST_CONTEXT.clear()
    LOGGER_STACK.set([])
    t0 = time.time()
    with OutputLogger(str(RUNS), None):
        if variant == "none":
            util, _ = run_task_without_injection_tasks(suite, pipe, user_task, RUNS, True, VER)
            sec = None
        else:
            u, s = run_task_with_injection_tasks(suite, pipe, user_task, attack, RUNS, True, [variant], VER)
            util = bool(list(u.values())[0]); sec = bool(list(s.values())[0])
    dt = time.time() - t0
    ctx = LAST_CONTEXT[-1] if LAST_CONTEXT else None
    if ctx is not None:
        CONTEXTS[variant] = ctx     # keep this run's live in-memory DuckDB for post-hoc inspection
    return {"variant": variant, "utility": bool(util), "security": sec, "secs": round(dt, 1),
            "fire_counts": dict(ctx.diagnostics.policy_fire_counts) if ctx else {},
            "registered": list(ctx.registered_policy_ids) if ctx else [],
            "facts": dict(ctx.extracted_facts) if ctx else {},
            "n_tool_calls": sum(1 for e in RUN_LOG if e["kind"] == "tool_call"),
            "n_blocked": sum(1 for e in RUN_LOG if e.get("blocked")),
            "log": list(RUN_LOG)}

RESULTS = {}
CONTEXTS = {}   # variant -> DFCBenchmarkContext; ctx.raw_conn is that run's live (in-memory) DuckDB
for v in variants:
    print(f"\n===== running {USER_TASK_ID} / {v} =====")
    r = run_variant(v)
    RESULTS[v] = r
    fired = {k: c for k, c in r["fire_counts"].items() if c}
    print(f"  utility={r['utility']}  security={r['security']}  "
          f"tool_calls={r['n_tool_calls']}  blocked={r['n_blocked']}  ({r['secs']}s)")
    print(f"  registered={r['registered']}  fired={fired}")

# archive the raw logs for this run
stamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
(OUT / f"run_{USER_TASK_ID}_{stamp}.json").write_text(json.dumps(RESULTS, indent=1, default=str), encoding="utf-8")
print("\nsaved ->", OUT / f"run_{USER_TASK_ID}_{stamp}.json")''')

md("""## Inspect the DuckDB instance

Query the live in-memory DuckDB that enforced a run — e.g. to see what the agent actually fetched /
downloaded (`DownloadFileThroughIdOutput`, `DownloadFileThroughUrlOutput`, `BrowseWebpageOutput`, ...), the
trusted `PreambleData`, or any `*Input` sink that was written. Works while the kernel is alive: it reads
`CONTEXTS[variant]` (populated by the run cell) and falls back to `LAST_CONTEXT[-1]`. **Restarting the kernel
discards these in-memory DBs** — for content after a restart, use the *Full agent transcript* cell instead.

- `db_tables()` — relations with row counts for the most recent run
- `show_table('DownloadFileThroughIdOutput')` — dump a relation's rows
- pass `variant='none'` / `variant='injection_task_5'` to pick a specific run""")
code(r'''# Inspect the live in-memory DuckDB that enforced a run (the kernel must still be alive).
# Uses CONTEXTS[variant] from the run cell; falls back to LAST_CONTEXT[-1] (the most recent run).

def _pick_ctx(variant=None):
    pool = CONTEXTS if ("CONTEXTS" in globals() and CONTEXTS) else {}
    if not pool and LAST_CONTEXT:
        pool = {CURRENT_VARIANT: LAST_CONTEXT[-1]}
    if not pool:
        raise RuntimeError("No live context. Run the task cell first (and don't restart the kernel).")
    if variant is None:
        variant = next(reversed(list(pool)))
    return variant, pool[variant]

def db_tables(variant=None, nonempty_only=True):
    """List relations in the run's DuckDB with row counts (non-empty by default)."""
    variant, ctx = _pick_ctx(variant)
    names = [ctx.runtime_schema.preamble_relation]
    names += [r.name for r in ctx.runtime_schema.tool_input_relations]
    names += [r.name for r in ctx.runtime_schema.tool_output_relations]
    print(f"=== DuckDB for {USER_TASK_ID} / {variant} ===")
    for name in names:
        try:
            n = ctx.raw_conn.execute(f'SELECT count(*) FROM "{name}"').fetchone()[0]
        except Exception:
            continue
        if n or not nonempty_only:
            print(f"  {name:44} {n}")

def show_table(relation, variant=None, limit=20, width=800):
    """Dump rows of one relation, e.g. show_table('DownloadFileThroughIdOutput')."""
    variant, ctx = _pick_ctx(variant)
    cur = ctx.raw_conn.execute(f'SELECT * FROM "{relation}" LIMIT {limit}')
    cols = [d[0] for d in cur.description]
    rows = cur.fetchall()
    print(f"=== [{variant}] {relation}: {len(rows)} row(s) ===")
    for row in rows:
        for c, v in zip(cols, row):
            if c.startswith("__dfc_") and c != "__dfc_raw_json":
                continue  # skip bookkeeping columns
            print(f"  {c}: {str(v)[:width]}")
        print("  " + "-" * 50)

_v, _ctx = _pick_ctx()
db_tables(_v)
print()
# auto-dump whatever the agent fetched / downloaded this run (the content sources)
for _rel in _ctx.runtime_schema.tool_output_relations:
    if any(k in _rel.name.lower() for k in ("download", "browse")):
        if _ctx.raw_conn.execute(f'SELECT count(*) FROM "{_rel.name}"').fetchone()[0]:
            show_table(_rel.name, _v)
print("\nuse show_table('<Relation>') or db_tables('<variant>') to inspect more "
      f"(variants available: {list(CONTEXTS) if 'CONTEXTS' in globals() and CONTEXTS else [CURRENT_VARIANT]})")''')

md("## Decision log — every tool call and policy verdict")
code(r'''def _short_args(a):
    try:
        return ", ".join(f"{k}={str(v)[:60]}" for k, v in a.items())
    except Exception:
        return str(a)[:120]

def print_decisions(variant):
    r = RESULTS[variant]
    print("=" * 88)
    print(f"{USER_TASK_ID} / {variant}    utility={r['utility']}    security={r['security']}")
    print("=" * 88)
    print("facts:", r["facts"])
    print("registered policies:", r["registered"])
    print("-" * 88)
    if not r["log"]:
        print("(no tool calls / decisions recorded)")
    for i, e in enumerate(r["log"]):
        if e["kind"] == "tool_call":
            print(f"[{i:02}] CALL  {e['tool']}({_short_args(e['args'])})  ->  "
                  f"{'!! BLOCKED' if e['blocked'] else 'allowed'}")
            for d in e["policies"]:
                print(f"         policy: {d}")
        elif e["kind"] == "source_required_sql":
            print(f"[{i:02}] SR-SQL [{e['status']}] sink={e['sink']}  ::  {e['sql']}")
            if e["message"]:
                print(f"         {e['message']}")
        else:
            print(f"[{i:02}] OUT   {e['tool']} -> {e['preview']}")

for v in variants:
    print_decisions(v); print()''')

md("""## Full agent transcript (from the saved trajectory)

The `RUN_LOG` above is the policy-decision view. This reads AgentDojo's full trajectory file for each run —
the agent's reasoning, every tool call (including any SOURCE-REQUIRED redirects handled before validation),
tool results, and the policy-violation feedback the agent received.""")
code(r'''def _text(c):
    if isinstance(c, str):
        return c
    if isinstance(c, list):
        return " ".join(str(b.get("content") or b.get("text") or "") if isinstance(b, dict) else str(b) for b in c)
    return str(c)

def _find_trace(variant):
    base = RUNS / pipe.name / SUITE / USER_TASK_ID
    cand = (base / "none" / "none.json") if variant == "none" else (base / ATTACK / f"{variant}.json")
    if cand.exists():
        return cand
    js = sorted(base.glob("**/*.json"), key=lambda p: p.stat().st_mtime, reverse=True) if base.exists() else []
    return js[0] if js else None

def dump_trace(variant, preview=500):
    p = _find_trace(variant)
    print("=" * 88); print(f"TRACE {USER_TASK_ID} / {variant}"); print(p); print("=" * 88)
    if not p or not p.exists():
        print("(no trajectory file found)"); return
    tj = json.load(open(p, encoding="utf-8"))
    for m in tj.get("messages", []):
        role = m.get("role")
        if role == "system":
            print(f"[system] {_text(m.get('content'))[:160]}")
        elif role == "user":
            print(f"[user] {_text(m.get('content'))[:preview]}")
        elif role == "assistant":
            txt = _text(m.get("content"))
            if txt.strip():
                print(f"[assistant] {txt[:preview]}")
            for tc in (m.get("tool_calls") or []):
                print(f"   -> {tc.get('function')}({tc.get('args')})")
        elif role == "tool":
            err = m.get("error")
            body = err if err else _text(m.get("content"))
            print(f"   [tool result] {'ERROR: ' if err else ''}{str(body)[:preview]}")

for v in variants:
    dump_trace(v); print()''')

md("""## Notes

- **No LLM writes policies here.** `manual_prepare_task` registers the PGNs straight from `runs_manual.json`
  for `CURRENT_VARIANT`; the only LLM call is the Qwen agent itself. To restore generation, run
  `DFCBenchmarkContext.prepare_task = _ORIG_PREPARE`.
- **Pick task / variants** in Config (`TASK_NUM`, `RUN_VARIANTS`). `none` = clean (measures utility),
  `injection_task_N` = under attack (measures security; `security=True` means the injection succeeded).
- **Policies + facts are per-variant** exactly as stored in the file. If a manual PGN can't register against
  the live schema, it's logged as FAILED and skipped (the run continues with the rest).
- Per-run logs are archived to `notebooks/one_task/out/`; full trajectories are under
  `runs/<pipeline>/<suite>/<task>/...`.""")

nb = {
    "cells": [
        ({"cell_type": "markdown", "metadata": {}, "source": src.splitlines(keepends=True)}
         if kind == "markdown" else
         {"cell_type": "code", "metadata": {}, "execution_count": None, "outputs": [],
          "source": src.splitlines(keepends=True)})
        for kind, src in cells
    ],
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python"},
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}
out = Path(__file__).resolve().parent / "one_task_manual.ipynb"
out.write_text(json.dumps(nb, indent=1, ensure_ascii=False), encoding="utf-8")
print("wrote", out, "with", len(cells), "cells")
